# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-10 12:16
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):


    ops = [
        (
            """
            ALTER FOREIGN TABLE "campusonline"."verteilerliste_person" OPTIONS (SET tablename 'VERTEILERLISTE_PERSON_PERS_V');
            """,
            """
            ALTER FOREIGN TABLE "campusonline"."verteilerliste_person" OPTIONS (SET tablename 'VERTEILERLISTE_PERSON_V');
            """,
        ),
        (
            """
            CREATE FOREIGN TABLE "campusonline"."verteilerliste_student" (
                PROFIL_NR numeric,
                PERS_NR numeric
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'VERTEILERLISTE_PERSON_STUD_V',
                db_url '{}'
            );
            """.format(
                settings.MULTICORN.get("campusonline")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "campusonline"."verteilerliste_student";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."campusonline_distributionlist_student" AS SELECT
                (profil_nr::integer)::varchar AS distributionlist_id,
                pers_nr::integer AS student_id
            FROM "campusonline"."verteilerliste_student"
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_distributionlist_student";
            """,
        ),
        (
            """
            CREATE UNIQUE INDEX campusonline_distributionlist_student_distributionlist_id_student_id_idx ON "public"."campusonline_distributionlist_student" ("distributionlist_id", "student_id");
            """,
            """
            DROP INDEX IF EXISTS campusonline_distributionlist_student_distributionlist_id_student_id_idx;
            """,
        ),
        (
            """
            CREATE INDEX campusonline_distributionlist_student_distributionlist_id_idx ON "public"."campusonline_distributionlist_student" ("distributionlist_id");
            """,
            """
            DROP INDEX IF EXISTS campusonline_distributionlist_student_distributionlist_id_idx;
            """,
        ),
        (
            """
            CREATE INDEX campusonline_distributionlist_student_student_id_idx ON "public"."campusonline_distributionlist_student" ("student_id");
            """,
            """
            DROP INDEX IF EXISTS campusonline_distributionlist_student_student_id_idx;
            """,
        ),
    ]

    dependencies = [
        ('campusonline', '0050_stud_photo'),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
