# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campusonline", "0052_person_extern")]

    operations = [
        migrations.CreateModel(
            name="External",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=256, null=True)),
                ("last_name", models.CharField(blank=True, max_length=256, null=True)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("W", "Female"), ("M", "Male")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                "db_table": "campusonline_external",
                "ordering": ("last_name", "first_name"),
                "managed": False,
            },
        )
    ]
