# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-16 09:19
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    ops = [
        (
            """
            CREATE FOREIGN TABLE "campusonline"."stud_impfstatus" (
                ST_PERSON_NR numeric,
                IMPFUNG_ERHALTEN varchar,
                STATUS varchar
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'STUD_IMPFSTATUS_V',
                db_url '{}'
            );
            """.format(
                settings.MULTICORN.get("campusonline")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "campusonline"."stud_impfstatus";
            """,
        ),
        (
            """
            DROP INDEX IF EXISTS campusonline_student_cardid_idx;
            """,
            """
            CREATE INDEX campusonline_student_cardid_idx ON "public"."campusonline_student" ("cardid");
            """,
        ),
        (
            """
            DROP INDEX IF EXISTS campusonline_student_matriculation_idx;
            """,
            """
            CREATE INDEX campusonline_student_matriculation_idx ON "public"."campusonline_student" ("matriculation");
            """,
        ),
        (
            """
            DROP INDEX IF EXISTS campusonline_student_id_idx;
            """,
            """
            CREATE INDEX campusonline_student_id_idx ON "public"."campusonline_student" ("id");
            """,
        ),
        (
            """
            DROP INDEX IF EXISTS campusonline_student_username_idx;
            """,
            """
            CREATE INDEX campusonline_student_username_idx ON "public"."campusonline_student" ("username");
            """,
        ),
        (
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_student";
            """,
            """
            CREATE MATERIALIZED VIEW "public"."campusonline_student" AS SELECT
                stud_nr::integer AS id,
                stud_mnr AS matriculation,
                stud_famnam AS last_name,
                stud_vorname AS first_name,
                stud_akadgrad AS title,
                stud_mifare AS cardid,
                stud_benutzername AS username,
                pers_profilbild AS avatar,
                email
            FROM "campusonline"."stud"
            WITH DATA;
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."campusonline_student" AS SELECT
                s.stud_nr::integer AS id,
                s.stud_mnr AS matriculation,
                s.stud_famnam AS last_name,
                s.stud_vorname AS first_name,
                s.stud_akadgrad AS title,
                s.stud_mifare AS cardid,
                s.stud_benutzername AS username,
                s.pers_profilbild AS avatar,
                s.email,
                UPPER(coalesce(si.impfung_erhalten, 'NEIN')) = 'JA' AS immunized
            FROM campusonline.stud s
                LEFT JOIN
                    campusonline.stud_impfstatus si on s.stud_nr::int = si.st_person_nr::int
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_student";
            """,
        ),
        (
            """
            CREATE INDEX campusonline_student_id_idx ON "public"."campusonline_student" ("id");
            """,
            """
            DROP INDEX IF EXISTS campusonline_student_id_idx;
            """,
        ),
        (
            """
            CREATE INDEX campusonline_student_matriculation_idx ON "public"."campusonline_student" ("matriculation");
            """,
            """
            DROP INDEX IF EXISTS campusonline_student_matriculation_idx;
            """,
        ),
        (
            """
            CREATE INDEX campusonline_student_cardid_idx ON "public"."campusonline_student" ("cardid");
            """,
            """
            DROP INDEX IF EXISTS campusonline_student_cardid_idx;
            """,
        ),
        (
            """
            CREATE INDEX campusonline_student_username_idx ON "public"."campusonline_student" ("username");
            """,
            """
            DROP INDEX IF EXISTS campusonline_student_username_idx;
            """,
        ),
        (
            """
            CREATE INDEX campusonline_student_email_idx ON "public"."campusonline_student" ("email");
            """,
            """
            DROP INDEX IF EXISTS campusonline_student_email_idx;
            """,
        ),
    ]

    dependencies = [
        ('campusonline', '0059_roomallocation'),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
