# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-03 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    ops = [
        (
            """
            CREATE INDEX campusonline_finalthesis_category_idx ON "public"."campusonline_finalthesis" ("category");
            """,
            """
            DROP INDEX IF EXISTS campusonline_finalthesis_category_idx;
            """,
        ),
    ]

    dependencies = [
        ('campusonline', '0060_stud_impf_status'),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
