# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-10 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    ops = [
        (
            """
            DROP INDEX IF EXISTS campusonline_finalthesis_id_idx;
            """,
            """
            CREATE INDEX campusonline_finalthesis_id_idx ON "public"."campusonline_finalthesis" ("id");
            """,
        ),
        (
            """
            DROP INDEX IF EXISTS campusonline_finalthesis_modified_idx;
            """,
            """
            CREATE INDEX campusonline_finalthesis_modified_idx ON "public"."campusonline_finalthesis" ("modified");
            """,
        ),
        (
            """
            DROP INDEX IF EXISTS campusonline_finalthesis_author_id_idx;
            """,
            """
            CREATE INDEX campusonline_finalthesis_author_id_idx ON "public"."campusonline_finalthesis" ("author_id");
            """,
        ),
        (
            """
            DROP INDEX IF EXISTS campusonline_finalthesis_tutor_id_idx;
            """,
            """
            CREATE INDEX campusonline_finalthesis_tutor_id_idx ON "public"."campusonline_finalthesis" ("tutor_id");
            """,
        ),
        (
            """
            DROP INDEX IF EXISTS campusonline_finalthesis_year_idx;
            """,
            """
            CREATE INDEX campusonline_finalthesis_year_idx ON "public"."campusonline_finalthesis" ("year");
            """,
        ),
        (
            """
            DROP INDEX IF EXISTS campusonline_finalthesis_organization_id_idx;
            """,
            """
            CREATE INDEX campusonline_finalthesis_organization_id_idx ON "public"."campusonline_finalthesis" ("organization_id");
            """,
        ),
        (
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_finalthesis";
            """,
            """
            CREATE MATERIALIZED VIEW "public"."campusonline_finalthesis" AS SELECT
                aa.ID::integer AS id,
                aa.STUDIENBEZEICHNUNG AS study_designation,
                aa.LETZTE_AENDERUNG::timestamptz AS modified,
                s.STUD_NR::integer AS author_id,
                regexp_split_to_array(trim(both ' ' from aa.AUTOREN), ';\s*') AS authors,
                aa.TITEL AS title,
                aa.KURZFASSUNG AS abstract,
                aa.SEITEN_ANZAHL::integer AS pages,
                p.PERS_NR::integer AS tutor_id,
                aa.ERSCHEINUNGSJAHR::integer AS year,
                aa.LINK AS url,
                aa.PUBLIZIERT AS category,
                o.NR::integer AS organization_id
            FROM "campusonline"."abschlussarbeiten" aa
            INNER JOIN "campusonline"."stud" s
                ON aa.AUTOR_ID::integer = s.STUD_NR::integer
            INNER JOIN "campusonline"."personen" p
                ON aa.BETREUER_ID::integer = p.PERS_NR::integer
            INNER JOIN "campusonline"."organisationen" o
                ON aa.ORGANISATIONS_ID::integer = o.NR::integer
            WITH DATA;
            """,
        ),
        (
            """
            ALTER FOREIGN TABLE "campusonline"."abschlussarbeiten" ADD COLUMN sprache varchar;
            """,
            """
            ALTER FOREIGN TABLE "campusonline"."abschlussarbeiten" DROP COLUMN sprache;
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."campusonline_finalthesis" AS
            SELECT
                aa.id::integer AS id,
                aa.studienbezeichnung AS study_designation,
                aa.letzte_aenderung::timestamp with time zone AS modified,
                s.stud_nr::integer AS author_id,
                aa.nachname_autor AS author_lastname,
                aa.vorname_autor AS author_firstname,
                NULLIF(TRIM(LEADING ' ' FROM SPLIT_PART(aa.autoren, ';', 2)), '') AS author_title,
                HSTORE(
                    ARRAY_AGG(LOWER(aa.sprache)),
                    ARRAY_AGG(aa.titel)
                ) AS title,
                HSTORE(
                    ARRAY_AGG(LOWER(aa.sprache)),
                    ARRAY_AGG(aa.kurzfassung)
                ) AS abstract,
                aa.seiten_anzahl::integer AS pages,
                p.pers_nr::integer AS tutor_id,
                aa.betreuer AS tutor_name,
                aa.erscheinungsjahr::integer AS year,
                aa.link AS url,
                aa.publiziert AS category,
                o.nr::integer AS organization_id
            FROM
                campusonline.abschlussarbeiten aa
            LEFT JOIN
                campusonline.stud s ON aa.autor_id::integer = s.stud_nr::integer
            LEFT JOIN
                campusonline.personen p ON aa.betreuer_id::integer = p.pers_nr::integer
            LEFT JOIN
                campusonline.organisationen o ON aa.organisations_id::integer = o.nr::integer
            WHERE
                aa.sprache IS NOT NULL
            GROUP BY
                id,
                study_designation,
                modified,
                author_id,
                author_lastname,
                author_firstname,
                author_title,
                pages,
                tutor_id,
                tutor_name,
                year,
                url,
                category,
                organization_id
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_finalthesis";
            """,
        ),
    ]

    dependencies = [
        ("campusonline", "0061_finalthesis_category_index"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
