# Generated by Django 2.2.26 on 2022-10-10 09:47

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    ops = [
        (
            """
            CREATE FOREIGN TABLE "campusonline"."lv_anw" (
                BUCHUNG_NR numeric,
                GRP_NR numeric,
                TERMIN_NR numeric,
                LV_BEGIN timestamp,
                LV_ENDE timestamp
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'LV_ANW',
                primary_key 'BUCHUNG_NR',
                db_url '{}'
            );
            """.format(
                settings.MULTICORN.get("campusonline")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "campusonline"."lv_anw";
            """,
        ),
    ]

    dependencies = [
        ("campusonline", "0063_immunization"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
