# Generated by Django 2.2.28 on 2022-10-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0064_lv_anw'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('term', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('onsite', models.BooleanField()),
            ],
            options={
                'db_table': 'campusonline_roomallocation',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='coursegroupterm',
            options={'get_latest_by': 'start', 'managed': False, 'ordering': ('start', 'end'), 'permissions': ()},
        ),
    ]
