# Generated by Django 2.2.28 on 2022-11-18 08:26

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0066_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('alpha2', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('alpha3', models.CharField(max_length=3)),
                ('name', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'db_table': 'campusonline_country',
                'ordering': ('alpha2',),
                'managed': False,
            },
        ),
    ]
