# Generated by Django 2.2.28 on 2023-01-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    ops = [
        (
            """
            ALTER FOREIGN TABLE "campusonline"."lv_anw"
                ADD COLUMN LEHRENDER_NR integer;
            """,
            """
            ALTER FOREIGN TABLE "campusonline"."lv_anw"
                DROP COLUMN LEHRENDER_NR;
            """,
        ),
    ]

    dependencies = [
        ("campusonline", "0067_country"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
