# Generated by Django 2.2.28 on 2023-02-02 07:59

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    ops = [
        (
            """
            CREATE FOREIGN TABLE "campusonline"."wlan_pwd" (
                BENUTZERNAME varchar,
                KENNWORT varchar,
                "CO-NETZ-ENABLED-B" varchar,
                "CO-NETZ-WLAN-C" integer
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'WLAN_PWD_V',
                primary_key 'BENUTZERNAME',
                db_url '{}'
            );
            """.format(
                settings.MULTICORN.get("campusonline")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "campusonline"."wlan_pwd";
            """,
        ),
    ]

    dependencies = [
        ("campusonline", "0069_exams"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
