# Generated by Django 2.2.28 on 2023-02-08 20:43

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campusonline", "0070_wlan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_start", models.DateTimeField()),
                ("registration_end", models.DateTimeField()),
                ("start", models.DateTimeField()),
                ("online_registration", models.BooleanField()),
                ("note", models.TextField()),
                ("valid", models.BooleanField()),
                ("deregistration_end", models.DateTimeField()),
                ("location", models.TextField()),
            ],
            options={
                "db_table": "campusonline_exam",
                "ordering": ("start",),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Examinee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_datetime", models.DateTimeField()),
                ("registration", models.DateField()),
                ("assessment_closure", models.DateField()),
            ],
            options={
                "db_table": "campusonline_examinee",
                "ordering": ("id",),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ExamineeStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short", models.CharField(max_length=8)),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                "db_table": "campusonline_examinee_status",
                "ordering": ("short",),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ExamMode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short", models.CharField(max_length=8)),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                "db_table": "campusonline_exam_mode",
                "ordering": ("short",),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ExamType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short", models.CharField(max_length=8)),
                ("name", django.contrib.postgres.fields.hstore.HStoreField()),
                ("certificate", django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                "db_table": "campusonline_exam_type",
                "ordering": ("short",),
                "managed": False,
            },
        ),
    ]
