# Generated by Django 2.2.28 on 2023-03-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    ops = [
        (
            """
            ALTER FOREIGN TABLE "campusonline"."wlan_pwd" OPTIONS (SET tablename 'MUG_WLAN_PWD_V', SET primary_key 'NR');
            """,
            """
            ALTER FOREIGN TABLE "campusonline"."wlan_pwd" OPTIONS (SET tablename 'WLAN_PWD_V', SET primary_key 'BENUTZERNAME');
            """,
        ),
    ]

    dependencies = [
        ("campusonline", "0073_person_titles"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
