# Generated by Django 2.2.28 on 2023-03-29 11:33

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    ops = [
        (
            """
            DROP INDEX IF EXISTS campusonline_organization_id_idx;
            """,
            """
            CREATE UNIQUE INDEX campusonline_organization_id_idx ON "public"."campusonline_organization" ("id");
            """,
        ),
        (
            """
            DROP INDEX IF EXISTS campusonline_organization_name_idx;
            """,
            """
            CREATE INDEX campusonline_organization_name_idx ON "public"."campusonline_organization" ("name");
            """,
        ),
        (
            """
            DROP INDEX IF EXISTS campusonline_organization_short_idx;
            """,
            """
            CREATE INDEX campusonline_organization_short_idx ON "public"."campusonline_organization" ("short");
            """,
        ),
        (
            """
            DROP INDEX IF EXISTS campusonline_organization_parent_id_idx;
            """,
            """
            CREATE INDEX campusonline_organization_parent_id_idx ON "public"."campusonline_organization" ("parent_id");
            """,
        ),
        (
            """
            DROP INDEX IF EXISTS campusonline_organization_category_idx;
            """,
            """
            CREATE INDEX campusonline_organization_category_idx ON "public"."campusonline_organization" ("category");
            """,
        ),
        (
            """
            DROP INDEX IF EXISTS campusonline_organization_sib_order_idx;
            """,
            """
            CREATE INDEX campusonline_organization_sib_order_idx ON "public"."campusonline_organization" ("sib_order");
            """,
        ),
        (
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_organization";
            """,
            """
            CREATE MATERIALIZED VIEW "public"."campusonline_organization" AS SELECT
                nr::integer AS id,
                org_name AS name,
                name_kurz AS short,
                basisorganisation::integer AS parent_id,
                sort_hierarchie::integer AS sib_order,
                typ AS category,
                adresse AS address,
                email_adresse AS email,
                telefon_nummer AS phone,
                www_homepage AS url,
                fax_nummer AS fax,
                sekretariat AS office
            FROM "campusonline"."organisationen"
            WITH DATA;
            """,
        ),
        (
            """
            ALTER FOREIGN TABLE "campusonline"."organisationen" ADD COLUMN ORGTYP_NR integer;
            """,
            """
            ALTER FOREIGN TABLE "campusonline"."organisationen" DROP COLUMN ORGTYP_NR;
            """,
        ),
        (
            """
            ALTER FOREIGN TABLE "campusonline"."organisationen" ADD COLUMN OEUG_FLAG varchar;
            """,
            """
            ALTER FOREIGN TABLE "campusonline"."organisationen" DROP COLUMN OEUG_FLAG;
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."campusonline_organization" AS SELECT
                nr::integer AS id,
                org_name AS name,
                name_kurz AS short,
                basisorganisation::integer AS parent_id,
                sort_hierarchie::integer AS sib_order,
                typ AS category,
                adresse AS address,
                email_adresse AS email,
                telefon_nummer AS phone,
                www_homepage AS url,
                fax_nummer AS fax,
                sekretariat AS office,
                orgtyp_nr AS type_id,
                (LOWER(oeug_flag) = 'j') AS university_law
            FROM "campusonline"."organisationen"
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_organization";
            """,
        ),
        (
            """
            CREATE UNIQUE INDEX campusonline_organization_id_idx ON "public"."campusonline_organization" ("id");
            """,
            """
            DROP INDEX IF EXISTS campusonline_organization_id_idx;
            """,
        ),
        (
            """
            CREATE INDEX campusonline_organization_name_idx ON "public"."campusonline_organization" ("name");
            """,
            """
            DROP INDEX IF EXISTS campusonline_organization_name_idx;
            """,
        ),
        (
            """
            CREATE INDEX campusonline_organization_short_idx ON "public"."campusonline_organization" ("short");
            """,
            """
            DROP INDEX IF EXISTS campusonline_organization_short_idx;
            """,
        ),
        (
            """
            CREATE INDEX campusonline_organization_parent_id_idx ON "public"."campusonline_organization" ("parent_id");
            """,
            """
            DROP INDEX IF EXISTS campusonline_organization_parent_id_idx;
            """,
        ),
        (
            """
            CREATE INDEX campusonline_organization_category_idx ON "public"."campusonline_organization" ("category");
            """,
            """
            DROP INDEX IF EXISTS campusonline_organization_category_idx;
            """,
        ),
        (
            """
            CREATE INDEX campusonline_organization_sib_order_idx ON "public"."campusonline_organization" ("sib_order");
            """,
            """
            DROP INDEX IF EXISTS campusonline_organization_sib_order_idx;
            """,
        ),
        (
            """
            CREATE INDEX campusonline_organization_university_law_idx ON "public"."campusonline_organization" ("university_law");
            """,
            """
            DROP INDEX IF EXISTS campusonline_organization_university_law_idx;
            """,
        ),
        (
            """
            CREATE FOREIGN TABLE "campusonline"."organisationstypen" (
                NR integer,
                NAME varchar,
                KURZBEZEICHNUNG varchar
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'ORGANISATIONSTYPEN_V',
                primary_key 'NR',
                db_url '{}'
            );
            """.format(
                settings.MULTICORN.get("campusonline")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "campusonline"."organisationstypen";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."campusonline_organization_type" AS SELECT
                nr::integer AS id,
                name,
                kurzbezeichnung AS short
            FROM "campusonline"."organisationstypen"
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_organization_type";
            """,
        ),
        (
            """
            CREATE UNIQUE INDEX campusonline_organization_type_id_idx ON "public"."campusonline_organization_type" ("id");
            """,
            """
            DROP INDEX IF EXISTS campusonline_organization_type_id_idx;
            """,
        ),
    ]

    dependencies = [
        ("campusonline", "0074_wlan_pwd_options"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
