# Generated by Django 2.2.28 on 2023-03-31 11:26

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    ops = [
        (
            """
            CREATE FOREIGN TABLE "campusonline"."oefos" (
                EDV_CODE integer,
                CODE varchar,
                KURZBEZEICHNUNG varchar,
                EBENE integer,
                TITEL_DE varchar,
                KURZTITEL_DE varchar,
                TITEL_EN varchar,
                KURZTITEL_EN varchar
            )
            SERVER sqlalchemy OPTIONS (
                tablename 'OEFOS_V',
                primary_key 'EDV_CODE',
                db_url '{}'
            );
            """.format(
                settings.MULTICORN.get("campusonline")
            ),
            """
            DROP FOREIGN TABLE IF EXISTS "campusonline"."oefos";
            """,
        ),
        (
            """
            CREATE MATERIALIZED VIEW "public"."campusonline_science_branch" AS SELECT
                edv_code AS id,
                code,
                ebene AS level,
                CASE ebene
                WHEN 1 THEN NULL
                WHEN 2 THEN SUBSTRING(edv_code::varchar for 1)::integer
                WHEN 3 THEN SUBSTRING(edv_code::varchar for 3)::integer
                WHEN 4 THEN SUBSTRING(edv_code::varchar for 4)::integer
                END AS parent_id,
                HSTORE(
                    array['de', 'en'],
                    array[titel_de, titel_en]
                ) AS name,
                HSTORE(
                    array['de', 'en'],
                    array[kurztitel_de, kurztitel_en]
                ) AS short
            FROM "campusonline"."oefos"
            WITH DATA;
            """,
            """
            DROP MATERIALIZED VIEW IF EXISTS "public"."campusonline_science_branch";
            """,
        ),
        (
            """
            CREATE UNIQUE INDEX campusonline_science_branch_id_idx ON "public"."campusonline_science_branch" ("id");
            """,
            """
            DROP INDEX IF EXISTS campusonline_science_branch_id_idx;
            """,
        ),
        (
            """
            CREATE INDEX campusonline_science_branch_parent_id_idx ON "public"."campusonline_science_branch" ("parent_id");
            """,
            """
            DROP INDEX IF EXISTS campusonline_science_branch_parent_id_idx;
            """,
        ),
        (
            """
            CREATE INDEX campusonline_science_branch_code_idx ON "public"."campusonline_science_branch" ("code");
            """,
            """
            DROP INDEX IF EXISTS campusonline_science_branch_code_idx;
            """,
        ),
    ]

    dependencies = [
        ("campusonline", "0075_organization_types"),
    ]

    operations = [
        migrations.RunSQL(
            [forward for forward, reverse in ops],
            [reverse for forward, reverse in reversed(ops)],
        )
    ]
