# Generated by Django 2.2.28 on 2026-04-23 09:03

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0078_linz'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER FOREIGN TABLE campusonline.organisationen
                        ADD COLUMN org_name_engl varchar
                    """,
                    reverse_sql="""
                        ALTER FOREIGN TABLE campusonline.organisationen
                        DROP COLUMN org_name_engl
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        DROP MATERIALIZED VIEW IF EXISTS public.campusonline_organization;

                        CREATE MATERIALIZED VIEW public.campusonline_organization
                        AS SELECT organisationen.nr AS id,
                            hstore(ARRAY['de'::text, 'en'::text], ARRAY[organisationen.org_name::text, organisationen.org_name_engl::text]) AS name,
                            organisationen.name_kurz AS short,
                            organisationen.basisorganisation::integer AS parent_id,
                            organisationen.sort_hierarchie AS sib_order,
                            organisationen.typ AS category,
                            organisationen.adresse AS address,
                            organisationen.email_adresse AS email,
                            organisationen.telefon_nummer AS phone,
                            organisationen.www_homepage AS url,
                            organisationen.fax_nummer AS fax,
                            organisationen.sekretariat AS office,
                            organisationen.orgtyp_nr AS type_id,
                            lower(organisationen.oeug_flag::text) = 'j'::text AS university_law
                        FROM campusonline.organisationen
                        WITH DATA;

                        CREATE INDEX campusonline_organization_category_idx ON public.campusonline_organization USING btree (category);
                        CREATE UNIQUE INDEX campusonline_organization_id_idx ON public.campusonline_organization USING btree (id);
                        CREATE INDEX campusonline_organization_name_idx ON public.campusonline_organization USING btree (name);
                        CREATE INDEX campusonline_organization_parent_id_idx ON public.campusonline_organization USING btree (parent_id);
                        CREATE INDEX campusonline_organization_short_idx ON public.campusonline_organization USING btree (short);
                        CREATE INDEX campusonline_organization_sib_order_idx ON public.campusonline_organization USING btree (sib_order);
                        CREATE INDEX campusonline_organization_university_law_idx ON public.campusonline_organization USING btree (university_law);
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW IF EXISTS public.campusonline_organization;

                        CREATE MATERIALIZED VIEW public.campusonline_organization
                        AS SELECT organisationen.nr AS id,
                            organisationen.org_name AS name,
                            organisationen.name_kurz AS short,
                            organisationen.basisorganisation::integer AS parent_id,
                            organisationen.sort_hierarchie AS sib_order,
                            organisationen.typ AS category,
                            organisationen.adresse AS address,
                            organisationen.email_adresse AS email,
                            organisationen.telefon_nummer AS phone,
                            organisationen.www_homepage AS url,
                            organisationen.fax_nummer AS fax,
                            organisationen.sekretariat AS office,
                            organisationen.orgtyp_nr AS type_id,
                            lower(organisationen.oeug_flag::text) = 'j'::text AS university_law
                        FROM campusonline.organisationen
                        WITH DATA;

                        CREATE INDEX campusonline_organization_category_idx ON public.campusonline_organization USING btree (category);
                        CREATE UNIQUE INDEX campusonline_organization_id_idx ON public.campusonline_organization USING btree (id);
                        CREATE INDEX campusonline_organization_name_idx ON public.campusonline_organization USING btree (name);
                        CREATE INDEX campusonline_organization_parent_id_idx ON public.campusonline_organization USING btree (parent_id);
                        CREATE INDEX campusonline_organization_short_idx ON public.campusonline_organization USING btree (short);
                        CREATE INDEX campusonline_organization_sib_order_idx ON public.campusonline_organization USING btree (sib_order);
                        CREATE INDEX campusonline_organization_university_law_idx ON public.campusonline_organization USING btree (university_law);
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="organization",
                    name="name",
                    field=django.contrib.postgres.fields.hstore.HStoreField(),
                )
            ],
        )
    ]
