# Generated by Django 2.2.28 on 2026-04-21 11:35

from django.db import migrations
from django.db.models import CharField

class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0079_add_multilingual_organization_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER FOREIGN TABLE campusonline.stockwerk
                        ADD COLUMN name_en varchar
                    """,
                    reverse_sql="""
                        ALTER FOREIGN TABLE campusonline.stockwerk
                        DROP COLUMN name_en
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        DROP MATERIALIZED VIEW IF EXISTS public.campusonline_floor;

                        CREATE MATERIALIZED VIEW public.campusonline_floor
                        AS SELECT stockwerk.nr AS id,
                            stockwerk.kurzbezeichnung AS short,
                            stockwerk.name,
                            stockwerk.name_en
                        FROM campusonline.stockwerk
                        WITH DATA;

                        CREATE UNIQUE INDEX campusonline_floor_id_idx ON public.campusonline_floor USING btree (id);
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW IF EXISTS public.campusonline_floor;

                        CREATE MATERIALIZED VIEW public.campusonline_floor
                        AS SELECT stockwerk.nr AS id,
                            stockwerk.kurzbezeichnung AS short,
                            stockwerk.name
                        FROM campusonline.stockwerk
                        WITH DATA;

                        CREATE UNIQUE INDEX campusonline_floor_id_idx ON public.campusonline_floor USING btree (id);
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="floor",
                    name="name_en",
                    field=CharField(max_length=256, blank=True, null=True),
                )
            ],
        )
    ]
