# Generated by Django 2.2.28 on 2026-04-23 09:03

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0079_add_multilingual_organization_name'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER FOREIGN TABLE campusonline.stockwerk
                        ADD COLUMN name_en varchar
                    """,
                    reverse_sql="""
                        ALTER FOREIGN TABLE campusonline.stockwerk
                        DROP COLUMN name_en
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        DROP MATERIALIZED VIEW IF EXISTS public.campusonline_floor;

                        CREATE MATERIALIZED VIEW public.campusonline_floor
                        AS SELECT stockwerk.nr AS id,
                            stockwerk.kurzbezeichnung AS short,
                            hstore(ARRAY['de'::text, 'en'::text], ARRAY[stockwerk.name::text, stockwerk.name_en::text]) AS name
                        FROM campusonline.stockwerk
                        WITH DATA;

                        CREATE UNIQUE INDEX campusonline_floor_id_idx ON public.campusonline_floor USING btree (id);
                    """,
                    reverse_sql="""
                        DROP MATERIALIZED VIEW IF EXISTS public.campusonline_floor;

                        CREATE MATERIALIZED VIEW public.campusonline_floor
                        AS SELECT stockwerk.nr AS id,
                            stockwerk.kurzbezeichnung AS short,
                            stockwerk.name
                        FROM campusonline.stockwerk
                        WITH DATA;

                        CREATE UNIQUE INDEX campusonline_floor_id_idx ON public.campusonline_floor USING btree (id);
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="floor",
                    name="name",
                    field=django.contrib.postgres.fields.hstore.HStoreField(),
                )
            ],
        )
    ]
