# Generated by Django 4.2.28 on 2026-05-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusonline', '0080_add_multilingual_floor_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False, 'ordering': ('order',)},
        ),
    ]
